//! The Postgres adapter, against the database in `DATABASE_URL` (the CI starts one). Without it, the test does nothing.
#![cfg(feature = "postgres")]

use cerne::application::{Outbox, OutboxEntry};
use cerne::postgres::{PostgresDatabase, PostgresOutbox};

#[tokio::test]
async fn the_outbox_stores_hands_out_and_marks_commands_in_a_transaction() {
    let Ok(database_url) = std::env::var("DATABASE_URL") else {
        return;
    };

    let database = PostgresDatabase::connect(&database_url, 2).await.unwrap();

    for statement in [
        "DROP TABLE IF EXISTS cerne_outbox",
        "CREATE TABLE cerne_outbox (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            command TEXT NOT NULL,
            json TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending',
            error TEXT
        )",
    ] {
        database.execute(sqlx::query(statement)).await.unwrap();
    }

    // --- Rolled back: nothing stored -----------------------------------------

    let transaction = database.begin().await.unwrap();
    let outbox = PostgresOutbox::new(transaction.clone());

    Outbox::<()>::store(&outbox, entry("ship_order"))
        .await
        .unwrap();
    drop(outbox);
    drop(transaction);

    let outbox = PostgresOutbox::new(database.clone());

    assert_eq!(Outbox::<()>::next_pending(&outbox).await.unwrap(), None);

    // --- Committed: stored, handed out, marked done --------------------------

    let transaction = database.begin().await.unwrap();

    Outbox::<()>::store(
        &PostgresOutbox::new(transaction.clone()),
        entry("ship_order"),
    )
    .await
    .unwrap();
    transaction.commit().await.unwrap();

    let stored_command = Outbox::<()>::next_pending(&outbox).await.unwrap().unwrap();

    assert_eq!(
        (
            stored_command.command.as_str(),
            stored_command.json.as_str()
        ),
        ("ship_order", "{}")
    );

    Outbox::<()>::mark_done(&outbox, stored_command.id)
        .await
        .unwrap();

    assert_eq!(Outbox::<()>::next_pending(&outbox).await.unwrap(), None);
}

fn entry(command: &str) -> OutboxEntry {
    OutboxEntry {
        command: command.into(),
        json: "{}".into(),
    }
}
