[package]
name = "cerne"
description = "Event Storming building blocks for Domain-Driven Design in Rust"
version.workspace = true
documentation = "https://docs.rs/cerne"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "../../README.en.md"
keywords.workspace = true
categories = ["rust-patterns"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
actix = "0.13"
anyhow = "1"
async-trait = "0.1"
cerne-macros = { version = "0.2.0", path = "../cerne-macros" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "time"] }
